version: '3.8'

services:
  qdrant:
    container_name: rag-qdrant-local
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY=true
      - QDRANT_SERVICE_ENABLE_TELEMETRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - rag-network

volumes:
  qdrant_data:

networks:
  rag-network:
    driver: bridge

  rag-app:
    container_name: rag-app
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - DEPLOYMENT_TYPE=local
      - ENVIRONMENT=development
      - WEBSOCKET_API_URL=ws://localhost:8501
    env_file:
      - ../.env
    networks:
      - rag-network
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 3

 